[package]
name = "git-activity-rs"
version = "0.1.0"
edition = "2021"
authors = ["Tom Heaton"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.25", features = ["derive"] }
